version: '3.4'

services:
  BasketDB:
    container_name: BasketDB
    restart: always
    ports:
      - "6379:6379"

  CatalogDB:
    restart: always
    ports:
      - "27017:27017"
    container_name: CatalogDB
    volumes:
      - mongo_data:/data/db

  DiscountDB:
    container_name: DiscountDB
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=DiscountDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  PGAdmin:
    container_name: PGAdmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspdotnet.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    volumes:
      - pgadmin_date:/root/.pgadmin

  Portainer:
    container_name: Portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalogapi:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://CatalogDB:27017"
    depends_on:
      - CatalogDB
    ports:
      - "8000:80"

  basketapi:
    container_name: BasketAPI
    depends_on :
      - BasketDB
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=BasketDB:6379"
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  discountapi:
    container_name: DiscountAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=DiscountDB;Port=5432;Database=DiscountDB;User Id=admin;Password=admin123"
    depends_on:
      - DiscountDB
    ports:
      - "8003:80"

